// data.jsx — fictional review data for CALPIS日誌
// Generic milky-drink reviews. NO real Calpis SKUs — variant names and tints are made up.

const REVIEWS = [
  { id: 'rich',   date: '2024.05.20', name: 'THE RICH',          variant: 'pet',     tint: '#fff5e8', accent: '#c89a6a', rating: 5.0, badge: 'NEW',
    oneLiner: '濃くてまろやかで幸せ…！', tags: ['新商品','濃厚','ご褒美'], cat: '新商品', mood: ['濃厚','甘め'], season: '通年',
    body: 'ひと口目からいつものより濃厚で、しっかりミルク感があってびっくり！甘さもやさしくて、後味はすっきり。お風呂上がりに飲むと最高にしあわせな気持ちになれます。これはリピ確定です…！！',
    sub: { 甘さ: 4.5, 濃さ: 5.0, さっぱり感: 3.5, ミルク感: 5.0, リピしたい度: 5.0 },
    info: { 発売日: '2024年4月16日', 内容量: '470ml', タイプ: '乳酸飲料' } },
  { id: 'soda',   date: '2024.05.15', name: 'SODA',              variant: 'pet',     tint: '#eaf4fc', accent: '#7aa9d9', rating: 4.0,
    oneLiner: 'シュワッと爽やか〜夏にぴったり', tags: ['定番','炭酸','スッキリ'], cat: '定番', mood: ['さっぱり','すっきり'], season: '夏' },
  { id: 'melon',  date: '2024.05.01', name: 'MELON',             variant: 'pet',     tint: '#e8f4e0', accent: '#88b878', rating: 4.5,
    oneLiner: 'メロンの香りが贅沢〜！', tags: ['期間限定','メロン','フルーティー'], cat: '期間限定', mood: ['フルーティー','甘め'], season: '春' },
  { id: 'rame',   date: '2024.04.22', name: 'ラムネ',             variant: 'pet',     tint: '#e0eff8', accent: '#7aa9d9', rating: 4.5,
    oneLiner: 'ラムネみたいでなつかしい味！', tags: ['期間限定','ラムネ','清涼感'], cat: '期間限定', mood: ['さっぱり','すっきり'], season: '夏' },
  { id: 'peach',  date: '2024.04.10', name: '白桃',               variant: 'pet',     tint: '#fde8ec', accent: '#e8a8b8', rating: 4.5,
    oneLiner: '白桃の香りがふわぁ〜と広がる！', tags: ['期間限定','白桃','さっぱり'], cat: '期間限定', mood: ['さっぱり','フルーティー'], season: '春' },
  { id: 'frozen', date: '2024.04.01', name: 'フローズン',          variant: 'cup',     tint: '#f0f6fc', accent: '#7aa9d9', rating: 4.5,
    oneLiner: 'シャリシャリで最高〜！', tags: ['フローズン','アイス','おすすめ'], cat: 'その他', mood: ['さっぱり','すっきり'], season: '夏' },
  { id: 'cafe',   date: '2024.03.18', name: 'カフェ',             variant: 'plastic', tint: '#e8d8c8', accent: '#9a7858', rating: 4.0,
    oneLiner: '甘さ控えめで大人な味わい', tags: ['コラボ','カフェ','大人向け'], cat: 'コラボ', mood: ['濃厚','甘め'], season: '冬' },
  { id: 'mikan',  date: '2024.03.03', name: 'みかん',             variant: 'pet',     tint: '#ffe8c8', accent: '#e8a858', rating: 4.0,
    oneLiner: 'みかんのやさしさ〜', tags: ['定番','みかん','せめ'], cat: '定番', mood: ['フルーティー','甘め'], season: '冬' },
  { id: 'yogurt', date: '2024.02.20', name: 'ヨーグルト味',        variant: 'pet',     tint: '#fdf4e0', accent: '#d8b878', rating: 4.0,
    oneLiner: 'ヨーグルト感が異なる！', tags: ['期間限定','ヨーグルト','せめ'], cat: '期間限定', mood: ['濃厚'], season: '通年' },
  { id: 'koime',  date: '2024.02.05', name: '濃いめ',             variant: 'carton',  tint: '#fff8ec', accent: '#c8a878', rating: 4.0,
    oneLiner: '濃いめの満足度がすごい！', tags: ['定番','濃いめ','リピート'], cat: '定番', mood: ['濃厚'], season: '通年' },
  { id: 'ichigo', date: '2024.01.15', name: 'いちご',             variant: 'pet',     tint: '#fde0e6', accent: '#d878a0', rating: 4.5,
    oneLiner: 'いちごミルクみたいで幸せ〜', tags: ['期間限定','いちご','せめ'], cat: '期間限定', mood: ['甘め','フルーティー'], season: '冬' },
  { id: 'classic',date: '2024.01.05', name: '濃いめ Classic',     variant: 'carton',  tint: '#fefaf0', accent: '#c89a6a', rating: 4.0,
    oneLiner: '濃いめの満足感がご褒美！', tags: ['ロング','定番','せめ'], cat: '定番', mood: ['濃厚'], season: '通年' },
  // older
  { id: 'water',  date: '2023.10.11', name: 'WATER',             variant: 'pet',     tint: '#eaf4fc', accent: '#7aa9d9', rating: 4.0,
    oneLiner: 'すっきり飲みやすい〜', tags: ['定番'], cat: '定番', mood: ['さっぱり'], season: '夏' },
  { id: 'grape',  date: '2023.06.18', name: 'グレープ',           variant: 'pet',     tint: '#ece0fa', accent: '#a888d8', rating: 4.0,
    oneLiner: 'ぶどうの甘酸っぱさ◎', tags: ['期間限定','ぶどう'], cat: '期間限定', mood: ['フルーティー'], season: '秋' },
  { id: 'sherbet',date: '2023.08.07', name: 'シャーベット',       variant: 'cup',     tint: '#f0f6fc', accent: '#7aa9d9', rating: 4.5,
    oneLiner: 'シャリシャリ夏の幸せ', tags: ['夏限定','アイス'], cat: 'その他', mood: ['さっぱり'], season: '夏' },
  { id: 'yoshi',  date: '2023.12.20', name: 'ほうじ茶',           variant: 'pet',     tint: '#f0e0c8', accent: '#a87858', rating: 4.0,
    oneLiner: 'ほっとする味わい〜', tags: ['コラボ','和風'], cat: 'コラボ', mood: ['濃厚'], season: '冬' },
  { id: 'yuzu',   date: '2023.01.09', name: 'ゆず',               variant: 'pet',     tint: '#fdf4d0', accent: '#c8a838', rating: 4.0,
    oneLiner: 'ゆずの香りが気持ちいい〜', tags: ['期間限定','ゆず'], cat: '期間限定', mood: ['さっぱり'], season: '冬' },
  { id: 'kucchi', date: '2023.02.14', name: 'カルピスキッス',     variant: 'pet',     tint: '#fde0e6', accent: '#d878a0', rating: 4.0,
    oneLiner: 'バレンタインっぽい甘さ◎', tags: ['期間限定'], cat: '期間限定', mood: ['甘め'], season: '冬' },
  { id: 'ichilem',date: '2023.04.03', name: 'いちご檸檬',         variant: 'pet',     tint: '#fde8d8', accent: '#e88a78', rating: 4.0,
    oneLiner: '甘酸っぱくてさっぱり', tags: ['期間限定'], cat: '期間限定', mood: ['さっぱり','フルーティー'], season: '春' },
  { id: 'mango',  date: '2024.12.24', name: '完熟マンゴー',       variant: 'pet',     tint: '#ffe0a8', accent: '#e89838', rating: 4.0,
    oneLiner: 'マンゴーの濃厚さに驚き', tags: ['期間限定','マンゴー'], cat: '期間限定', mood: ['フルーティー','濃厚'], season: '夏' },
  { id: 'lassi',  date: '2024.10.02', name: 'ラッシー',           variant: 'pet',     tint: '#fefaee', accent: '#c8b878', rating: 4.0,
    oneLiner: '異国の味わい〜', tags: ['コラボ'], cat: 'コラボ', mood: ['濃厚'], season: '通年' },
  { id: 'sakura', date: '2024.11.15', name: '桜もち',             variant: 'pet',     tint: '#fde0e6', accent: '#e8a8b8', rating: 4.0,
    oneLiner: '桜の和風な甘さ', tags: ['期間限定','和'], cat: '期間限定', mood: ['甘め'], season: '春' },
  { id: 'mokka',  date: '2024.09.10', name: 'モカ',               variant: 'pet',     tint: '#e0d0c0', accent: '#8a6848', rating: 4.0,
    oneLiner: 'コーヒーラテっぽい〜', tags: ['コラボ'], cat: 'コラボ', mood: ['濃厚'], season: '秋' },
  { id: 'mintc',  date: '2024.08.14', name: 'ミントチョコ',       variant: 'cup',     tint: '#dceee0', accent: '#7ab898', rating: 4.5,
    oneLiner: 'ミントが涼しい〜', tags: ['夏限定','コラボ'], cat: 'コラボ', mood: ['さっぱり'], season: '夏' },
  { id: 'pinea',  date: '2024.07.03', name: 'パイナップル',       variant: 'pet',     tint: '#fef4c8', accent: '#d8a858', rating: 4.0,
    oneLiner: 'トロピカルでさっぱり', tags: ['期間限定'], cat: '期間限定', mood: ['フルーティー','さっぱり'], season: '夏' },
  { id: 'kuro',   date: '2024.06.05', name: 'ブラックチェリー',   variant: 'pet',     tint: '#f8d8d8', accent: '#a85868', rating: 4.5,
    oneLiner: 'チェリーの甘酸っぱさ◎', tags: ['期間限定'], cat: '期間限定', mood: ['フルーティー'], season: '夏' },
  { id: 'kinako', date: '2022.10.05', name: 'きなこ',             variant: 'pet',     tint: '#f0e0c8', accent: '#a87858', rating: 3.5,
    oneLiner: '香ばしくて和風', tags: ['コラボ'], cat: 'コラボ', mood: ['濃厚'], season: '秋' },
  { id: 'green',  date: '2022.06.12', name: '抹茶',               variant: 'pet',     tint: '#dce8c8', accent: '#7a9858', rating: 4.0,
    oneLiner: '抹茶の苦みがいい〜', tags: ['コラボ'], cat: 'コラボ', mood: ['濃厚'], season: '夏' },
  { id: 'oden',   date: '2022.03.10', name: 'オレンジ',           variant: 'pet',     tint: '#ffe0a8', accent: '#e89838', rating: 4.0,
    oneLiner: 'オレンジ感たっぷり', tags: ['定番'], cat: '定番', mood: ['フルーティー'], season: '春' },
  { id: 'roul',   date: '2021.07.01', name: 'ルレモン',           variant: 'pet',     tint: '#fdf4d0', accent: '#c8a838', rating: 4.0,
    oneLiner: 'レモンの爽やかさ', tags: ['期間限定'], cat: '期間限定', mood: ['さっぱり'], season: '夏' },
  { id: 'plum',   date: '2021.04.15', name: '梅',                 variant: 'pet',     tint: '#ffe0e8', accent: '#d878a0', rating: 4.0,
    oneLiner: '梅の和風な味わい', tags: ['期間限定','和'], cat: '期間限定', mood: ['さっぱり'], season: '春' },
  { id: 'aloe',   date: '2020.06.04', name: 'アロエ',             variant: 'pet',     tint: '#e8f4e0', accent: '#88b878', rating: 4.0,
    oneLiner: 'プチプチ食感が楽しい〜', tags: ['定番'], cat: '定番', mood: ['さっぱり'], season: '夏' },
];

window.REVIEWS = REVIEWS;
window.CATEGORIES = ['すべて','定番','期間限定','コラボ','その他'];
window.MOODS = ['さっぱり','濃厚','フルーティー','甘め','すっきり'];
window.SEASONS = ['春','夏','秋','冬','通年'];
